# Generated by Django 5.0.14 on 2026-06-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False, help_text='Indicates whether the article has been approved by an editor.'),
        ),
    ]
